// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class Poly_GP
{
        public const string achievement_stage_1 = "CgkIgoLo6cUQEAIQAA"; // <GPGSID>
        public const string achievement_stage_2 = "CgkIgoLo6cUQEAIQAQ"; // <GPGSID>
        public const string achievement_stage_3 = "CgkIgoLo6cUQEAIQAg"; // <GPGSID>
        public const string achievement_stage_4 = "CgkIgoLo6cUQEAIQAw"; // <GPGSID>
        public const string achievement_stage_5 = "CgkIgoLo6cUQEAIQBA"; // <GPGSID>
        public const string leaderboard_kill = "CgkIgoLo6cUQEAIQBQ"; // <GPGSID>

}

